xychart-beta
    title "Relative cost to fix a defect, by where it is found"
    x-axis ["While typing", "Unit test", "Integration", "CI black-box", "Staging", "Production"]
    y-axis "Relative cost" 0 --> 100
    bar [1, 2, 5, 10, 30, 100]
