flowchart TB
    main["src/main<br/>application"]
    fx["src/testFixtures<br/>QuoteTestData, StubRateGateway,<br/>PostgresContainer"]
    unit["src/test (UNIT)<br/>JUnit, AssertJ, Mockito, ArchUnit<br/>NO Spring test support"]
    integ["src/integrationTest<br/>+ webmvc-test, data-jpa-test,<br/>Testcontainers, WireMock"]
    sys["src/systemTest (to be removed)<br/>+ @SpringBootTest, TestRestTemplate"]
    main --> fx
    main --> unit
    fx --> unit
    main --> integ
    fx --> integ
    main --> sys
    fx --> sys
