xychart-beta
    title "Load shapes over time (virtual users)"
    x-axis ["0", "5", "10", "15", "20", "25", "30", "35", "40"]
    y-axis "Users" 0 --> 100
    line [0, 20, 20, 20, 20, 20, 20, 20, 0]
    line [0, 20, 40, 60, 80, 100, 100, 100, 0]
    line [0, 10, 10, 90, 10, 10, 90, 10, 0]
